In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "city" : ["new york","chicago","orlando","baltimore"],
    "temperature": [21,14,35,32]
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           32

In [3]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","san fransisco"],
    "humidity": [65,68,71]
})
df2

            city  humidity
0        chicago        65
1       new york        68
2  san fransisco        71

In [4]:
df3 = pd.merge(df1,df2, on = "city", how="outer", indicator = True)
df3

            city  temperature  humidity      _merge
0      baltimore         32.0       NaN   left_only
1        chicago         14.0      65.0        both
2       new york         21.0      68.0        both
3        orlando         35.0       NaN   left_only
4  san fransisco          NaN      71.0  right_only

In [6]:
df1 = pd.DataFrame({
    "city" : ["new york","chicago","orlando","baltimore"],
    "temperature": [21,14,35,32],
    "humidity": [65,68,71,75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           32        75

In [7]:
df2 = pd.DataFrame({
    "city" : ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [9]:
df3 = pd.merge(df1,df2, on = "city", how="outer", suffixes = '')
df3

        city  temperature_x  humidity_x  temperature_y  humidity_y
0  baltimore           32.0        75.0            NaN         NaN
1    chicago           14.0        68.0           21.0        65.0
2   new york           21.0        65.0           14.0        68.0
3    orlando           35.0        71.0            NaN         NaN
4  san diego            NaN         NaN           35.0        71.0