In [1]:
import pandas as pd

In [8]:
df = pd.read_excel(r"E:\datasets\stocks_stack.xlsx",header=[0,1], index_col=0)
df

              Price                  Price to earnings ratio (P/E)         \
Company    Facebook Google Microsoft                      Facebook Google
2017-06-05      155    955        66                         37.10   32.0
2017-06-06      150    987        69                         36.98   31.3
2017-06-07      153    963        62                         36.78   31.7
2017-06-08      155   1000        61                         36.11   31.2
2017-06-09      156   1012        66                         37.07   30.0


Company    Microsoft
2017-06-05     30.31
2017-06-06     30.56
2017-06-07     30.46
2017-06-08     30.11
2017-06-09     31.00

In [26]:
df_stacked = df.stack()
df_stacked

C:\Users\Jeet\AppData\Local\Temp\ipykernel_8768\4229929500.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = df.stack()

                      Price  Price to earnings ratio (P/E)
           Company
2017-06-05 Facebook     155                          37.10
           Google       955                          32.00
           Microsoft     66                          30.31
2017-06-06 Facebook     150                          36.98
           Google       987                          31.30
           Microsoft     69                          30.56
2017-06-07 Facebook     153                          36.78
           Google       963                          31.70
           Microsoft     62                          30.46
2017-06-08 Facebook     155                          36.11
           Google      1000                          31.20
           Microsoft     61                          30.11
2017-06-09 Facebook     156                          37.07
           Google      1012                          30.00
           Microsoft     66                          31.00

In [27]:
df_stacked.unstack()

              Price                  Price to earnings ratio (P/E)         \
Company    Facebook Google Microsoft                      Facebook Google
2017-06-05      155    955        66                         37.10   32.0
2017-06-06      150    987        69                         36.98   31.3
2017-06-07      153    963        62                         36.78   31.7
2017-06-08      155   1000        61                         36.11   31.2
2017-06-09      156   1012        66                         37.07   30.0


Company    Microsoft
2017-06-05     30.31
2017-06-06     30.56
2017-06-07     30.46
2017-06-08     30.11
2017-06-09     31.00