In [1]:
import pandas as pd

In [2]:
india_weather = pd.DataFrame({
    "city":["mumbai","delhi","bangalore"],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
india_weather

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [3]:
us_weather = pd.DataFrame({
    "city":["new york","chicago","orlando"],
    "temperature":[21,14,35],
    "humidity":[68,65,75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [4]:
df = pd.concat([india_weather,us_weather], ignore_index = True)
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
3   new york           21        68
4    chicago           14        65
5    orlando           35        75

In [5]:
df = pd.concat([india_weather,us_weather],keys=["india","us"])
df

              city  temperature  humidity
india 0     mumbai           32        80
      1      delhi           45        60
      2  bangalore           30        78
us    0   new york           21        68
      1    chicago           14        65
      2    orlando           35        75

In [6]:
df.loc["india"]

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [7]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [8]:
temp_df= pd.DataFrame({
    "city":["delhi","mumbai","Kolkata"],
    "temperature":[35,32,36]
}, index=[0,1,2])
temp_df

      city  temperature
0    delhi           35
1   mumbai           32
2  Kolkata           36

In [9]:
wind_df= pd.DataFrame({
    "city":["Kolkata","delhi"],
    "windspeed":[25,27]
}, index=[2,0])
wind_df

      city  windspeed
2  Kolkata         25
0    delhi         27

In [10]:
df = pd.concat([temp_df,wind_df], axis= 1)
df

      city  temperature     city  windspeed
0    delhi           35    delhi       27.0
1   mumbai           32      NaN        NaN
2  Kolkata           36  Kolkata       25.0

In [11]:
temp_df

      city  temperature
0    delhi           35
1   mumbai           32
2  Kolkata           36

In [13]:
s = pd.Series(["Humid","Dry","Rain"],name = "event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [16]:
df = pd.concat([temp_df,s],axis = 1)
df

      city  temperature  event
0    delhi           35  Humid
1   mumbai           32    Dry
2  Kolkata           36   Rain