In [1]:
import pandas as pd

In [2]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

In [3]:
df = pd.DataFrame(weather_data)
# df
df = pd.read_csv(r"E:\datasets\weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
df.shape  # rows, columns = df.shape

(6, 4)

In [5]:
df.head() # df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [6]:
df.tail() # df.tail(2)

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [7]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [8]:
df.temperature # df['temperature']

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [9]:
df[['day','temperature', 'windspeed']]

        day  temperature  windspeed
0  1/1/2017           32          6
1  1/2/2017           35          7
2  1/3/2017           28          2
3  1/4/2017           24          7
4  1/5/2017           32          4
5  1/6/2017           31          2

In [10]:
df.temperature.max()

35

In [11]:
df.temperature.min()

24

In [12]:
df.temperature.mean()

30.333333333333332

In [13]:
df.temperature.std()

3.8297084310253524

In [14]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [15]:
df[df.temperature > 30]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [16]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [17]:
df[df.temperature == df.temperature.min()]

        day  temperature  windspeed event
3  1/4/2017           24          7  Snow

In [18]:
df['day'][df.temperature == df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [19]:
df[['day','temperature']][df.temperature == df.temperature.max()]

        day  temperature
1  1/2/2017           35

In [20]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [21]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [28]:
df.set_index('event', inplace=True)

In [29]:
df

       temperature  windspeed
event
Rain            32          6
Sunny           35          7
Snow            28          2
Snow            24          7
Rain            32          4
Sunny           31          2

In [30]:
df.loc['Snow']

       temperature  windspeed
event
Snow            28          2
Snow            24          7