In [1]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\jeet\anaconda3\lib\site-packages (1.2.0)

In [2]:
import pandas as pd
import sqlalchemy

In [3]:
engine = sqlalchemy.create_engine("mysql+pymysql://root:root@localhost:3307/pandas")

In [7]:
df = pd.read_sql_table("customers", engine, columns=['name', 'phone_number'])

print(df)

     name phone_number
0  Donald   9876543210
1    Bill   9123456780
2    Modi   9988776655

In [5]:
df = pd.read_sql("SELECT name, phone_number FROM customers", engine)

print(df)

     name phone_number
0  Donald   9876543210
1    Bill   9123456780
2    Modi   9988776655

In [11]:
query = '''
SELECT customers.name,customers.phone_number,orders.name,orders.amount
FROM customers INNER JOIN orders
ON customers.id = orders.customer_id
'''
df = pd.read_sql_query(query,engine)
df

     name phone_number          name  amount
0  Donald   9876543210  Google Pixel   950.0
1    Bill   9123456780      Yoga Mat    20.0
2    Modi   9988776655  Fossil Watch   120.0

In [15]:
df = pd.DataFrame({
    'Customer Name': ['Jeet Sil', 'Jhony Dep'],
    'Customer Phone': ['789010401','8794567589']
})
df

  Customer Name Customer Phone
0      Jeet Sil      789010401
1     Jhony Dep     8794567589

In [19]:
df.rename(columns={
    'Customer Name': 'name',
    'Customer Phone': 'phone_number'
},inplace=True)
df

        name phone_number
0   Jeet Sil    789010401
1  Jhony Dep   8794567589

In [22]:
df.to_sql(
    name='customers',
    con=engine,
    index= False,
    if_exists='append'
)

2